version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5051:5050"
    volumes:
      - ../backend:/app
    environment:
      - NODE_ENV=development
      - PORT=5050
      - MONGO_URI=mongodb://mongo:27017/influencerz-hub

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: