
services:
  backend:
    container_name: influencerz-hub-backend
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5051:5050"
    volumes:
      - ../backend:/app
    environment:
      - NODE_ENV=development
      - PORT=5050
      - MONGO_URI=mongodb://mongo:27017/influencerz-hub
      - REDIS_URI=redis://redis:6379

  mongo:
    image: mongo:latest
    container_name: influencerz-hub-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: influencerz-hub-redis
    ports:
      - "6379:6379"

volumes:
  mongo-data: